
/* Modelo Relacional: */

CREATE TABLE CLIENTES (
    ID_CLIENTE INTEGER AUTO_INCREMENT PRIMARY KEY,
    CLI_BAIRRO VARCHAR (50) NOT NULL,
    CLI_NUMERO VARCHAR (5) NOT NULL,
    CLI_CIDADE VARCHAR (50) NOT NULL,
    CLI_CEP VARCHAR (9) NOT NULL,
    CLI_ESTADO VARCHAR (2) NOT NULL,
    CLI_NOME VARCHAR(255) NOT NULL,
    CLI_CPF CHAR (11)  UNIQUE,
    CLI_RG VARCHAR (255) UNIQUE,
    CLI_NASCIMENTO DATE NOT NULL,
    CLI_CELULAR VARCHAR(15) UNIQUE,
    CLI_EMAIL VARCHAR(100) UNIQUE,
    CLI_SEXO ENUM('M', 'F', 'I') NOT NULL,
    CLI_SENHA VARCHAR(100) NOT NULL
);

CREATE TABLE FUNCIONARIOS (
    ID_FUNCIONARIO INTEGER AUTO_INCREMENT PRIMARY KEY,
    FUN_NOME VARCHAR(255) NOT NULL,
    FUN_CPF CHAR (11)  UNIQUE,
    FUN_RG VARCHAR (255) UNIQUE,
    FUN_BAIRRO VARCHAR (50) NOT NULL,
    FUN_NUMERO VARCHAR (5) NOT NULL,
    FUN_CIDADE VARCHAR (50) NOT NULL,
    FUN_CEP VARCHAR (9) NOT NULL,
    FUN_ESTADO VARCHAR (2) NOT NULL,
    FUN_SEXO ENUM('M', 'F', 'I') NOT NULL,
    FUN_SENHA VARCHAR(100) NOT NULL,
    FUN_EMAIL VARCHAR(100) UNIQUE,
    FUN_CELULAR VARCHAR(15) UNIQUE,
    FUN_NASCIMENTO DATE NOT NULL,
    FUN_TIPO VARCHAR(50) NOT NULL
);

CREATE TABLE FEEDBACKS (
    ID_FEEDBACK INT AUTO_INCREMENT PRIMARY KEY,
    FK_CLIENTES_ID_CLIENTE INTEGER NOT NULL,
    FEE_COMENTARIO VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUTOS (
    PRD_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRD_NOME VARCHAR(25) NOT NULL,
    PRD_PRECO DECIMAL(6,2) NOT NULL,
    PRD_QUANTIDADE INT NOT NULL
);

CREATE TABLE PEDIDOS (
    ID_PEDIDOS INT AUTO_INCREMENT PRIMARY KEY,
    FK_PRODUTOS_PRD_ID INT NOT NULL,
    FK_RESERVAS_ID_RESERVA INT NOT NULL,
    PED_VALOR DECIMAL(6,2) NOT NULL,
    PED_QTD INT NOT NULL
);

CREATE TABLE PAGAMENTOS (
    PAG_ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_RESERVAS_ID_RESERVA INT NOT NULL,
    PAG_VALOR_TOTAL DECIMAL(6,2) NOT NULL,
    PAG_VALOR_PEDIDO DECIMAL(6,2) NOT NULL,
    PAG_METODO VARCHAR(25) NOT NULL
);

CREATE TABLE QUARTOS (
    ID_QUARTO INT NOT NULL PRIMARY KEY,
    QRT_CAPACIDADE INT NOT NULL,
    QRT_TIPO_CAMA VARCHAR(80) NOT NULL,
    QRT_DISPONIVEL BOOLEAN DEFAULT 1,
    QRT_PRECO_DIARIA DEC(6,2) NOT NULL
);

CREATE TABLE RESERVAS (
    ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
    FK_QUARTOS_ID_QUARTO INT NOT NULL,
    FK_CLIENTES_ID_CLIENTE INTEGER NOT NULL,
    RES_CHECKIN DATETIME NOT NULL,
    RES_QTD_HOSPEDES INT NOT NULL,
    RES_CHECKOUT DATETIME NOT NULL
);

CREATE TABLE LIMPEZAS (
    ID_LIMPEZA INT AUTO_INCREMENT PRIMARY KEY,
    FK_FUNCIONARIOS_ID_FUNCIONARIO INTEGER NOT NULL,
    FK_QUARTOS_ID_QUARTO INT NOT NULL,
    LIM_LIMPO BOOLEAN NOT NULL,
    LIM_NOME_TAREFA VARCHAR(50) NOT NULL,
    LIM_DATA_TAREFA DATETIME NOT NULL
);
 
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACKS_2
    FOREIGN KEY (FK_CLIENTES_ID_CLIENTE)
    REFERENCES CLIENTES (ID_CLIENTE)
    ON DELETE RESTRICT;
 
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_2
    FOREIGN KEY (FK_PRODUTOS_PRD_ID)
    REFERENCES PRODUTOS (PRD_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_3
    FOREIGN KEY (FK_RESERVAS_ID_RESERVA)
    REFERENCES RESERVAS (ID_RESERVA)
    ON DELETE CASCADE;
 
ALTER TABLE PAGAMENTOS ADD CONSTRAINT FK_PAGAMENTOS_2
    FOREIGN KEY (FK_RESERVAS_ID_RESERVA)
    REFERENCES RESERVAS (ID_RESERVA)
    ON DELETE RESTRICT;
 
ALTER TABLE RESERVAS ADD CONSTRAINT FK_RESERVAS_2
    FOREIGN KEY (FK_QUARTOS_ID_QUARTO)
    REFERENCES QUARTOS (ID_QUARTO)
    ON DELETE CASCADE;
 
ALTER TABLE RESERVAS ADD CONSTRAINT FK_RESERVAS_3
    FOREIGN KEY (FK_CLIENTES_ID_CLIENTE)
    REFERENCES CLIENTES (ID_CLIENTE)
    ON DELETE RESTRICT;
 
ALTER TABLE LIMPEZAS ADD CONSTRAINT FK_LIMPEZAS_2
    FOREIGN KEY (FK_FUNCIONARIOS_ID_FUNCIONARIO)
    REFERENCES FUNCIONARIOS (ID_FUNCIONARIO)
    ON DELETE RESTRICT;
 
ALTER TABLE LIMPEZAS ADD CONSTRAINT FK_LIMPEZAS_3
    FOREIGN KEY (FK_QUARTOS_ID_QUARTO)
    REFERENCES QUARTOS (ID_QUARTO)
    ON DELETE RESTRICT;