/* Modelo Relacional: */

CREATE TABLE CLIENTES (
    CLI_BAIRRO VARCHAR (50) NOT NULL,
    CLI_NUMERO VARCHAR (5) NOT NULL,
    CLI_CIDADE VARCHAR (50) NOT NULL,
    CLI_CEP VARCHAR (9) NOT NULL,
    CLI_ESTADO VARCHAR (2) NOT NULL,
    CLI_NOME VARCHAR(255) NOT NULL,
    CLI_CPF CHAR (11)  NOT NULL,
    CLI_RG VARCHAR (255) NOT NULL,
    CLI_NASCIMENTO DATE NOT NULL,
    CLI_CELULAR VARCHAR(15) NOT NULL,
    CLI_EMAIL VARCHAR(100) NOT NULL,
    CLI_SEXO VARCHAR (10) NOT NULL,
    CLI_SENHA VARCHAR(100) NOT NULL,
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE FUNCIONARIOS (
    FUN_NOME VARCHAR(255) NOT NULL,
    FUN_CPF CHAR (11)  NOT NULL,
    FUN_RG VARCHAR (255) NOT NULL,
    FUN_BAIRRO VARCHAR (50) NOT NULL,
    FUN_NUMERO VARCHAR (5) NOT NULL,
    FUN_CIDADE VARCHAR (50) NOT NULL,
    FUN_CEP VARCHAR (9) NOT NULL,
    FUN_ESTADO VARCHAR (2) NOT NULL,
    FUN_SEXO VARCHAR (10) NOT NULL,
    FUN_SENHA VARCHAR(100) NOT NULL,
    FUN_EMAIL VARCHAR(100) NOT NULL,
    FUN_CELULAR VARCHAR(15) NOT NULL,
    FUN_NASCIMENTO DATE NOT NULL,
    FUN_TIPO VARCHAR(50) NOT NULL,
    ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE FEEDBACKS (
    ID_FEEDBACK INT AUTO_INCREMENT PRIMARY KEY,
    FEE_COMENTARIO VARCHAR(255) NOT NULL,
    FK_CLIENTES_ID_CLIENTE INT
);

CREATE TABLE PRODUTOS (
    PRD_ID INTEGER NOT NULL PRIMARY KEY,
    PRD_NOME VARCHAR(25) NOT NULL,
    PRD_PRECO DECIMAL(3,2) NOT NULL,
    PRD_QUANTIDADE INT NOT NULL,
    FK_PEDIDOS_ID_PEDIDOS INT
);

CREATE TABLE PEDIDOS (
    PED_VALOR DECIMAL(10,2) NOT NULL,
    ID_PEDIDOS INT AUTO_INCREMENT PRIMARY KEY,
    PED_QTD INT NOT NULL,
    FK_CLIENTES_ID_CLIENTE INT
);

CREATE TABLE PAGAMENTOS (
    PAG_ID INT AUTO_INCREMENT PRIMARY KEY,
    PAG_VALOR_TOTAL DECIMAL(4,2) NOT NULL,
    PAG_VALOR_PEDIDO DECIMAL(3,2) NOT NULL,
    PAG_METODO VARCHAR(25) NOT NULL,
    FK_CLIENTES_ID_CLIENTE INT
);

CREATE TABLE QUARTOS (
    ID_QUARTO INT NOT NULL PRIMARY KEY,
    QRT_CAPACIDADE INTEGER NOT NULL,
    QRT_TIPO_CAMA VARCHAR(80) NOT NULL,
    QRT_DISPONIVEL BOOLEAN NOT NULL,
    QRT_PRECO_DIARIA DEC(10,2) NOT NULL
);

CREATE TABLE RESERVAS_RESERVA (
    RES_CHECKIN DATETIME NOT NULL,
    RES_CHECKOUT DATETIME NOT NULL,
    ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
    RES_QTD_HOSPEDES INT NOT NULL,
    FK_CLIENTES_ID_CLIENTE INT,
    FK_QUARTOS_ID_QUARTO INT
);

CREATE TABLE LIMPEZAS_FAZ_MANUTENCAO (
    ID_LIMPEZA INT AUTO_INCREMENT PRIMARY KEY,
    LIM_LIMPO BOOLEAN NOT NULL,
    LIM_NOME_TAREFA VARCHAR(50) NOT NULL,
    LIM_DATA_TAREFA DATETIME NOT NULL,
    FK_FUNCIONARIOS_ID_FUNCIONARIO INT,
    FK_QUARTOS_ID_QUARTO INT
);
 
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACKS_2
    FOREIGN KEY (FK_CLIENTES_ID_CLIENTE)
    REFERENCES CLIENTES (ID_CLIENTE)
    ON DELETE CASCADE;
 
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_2
    FOREIGN KEY (FK_PEDIDOS_ID_PEDIDOS)
    REFERENCES PEDIDOS (ID_PEDIDOS)
    ON DELETE RESTRICT;
 
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_2
    FOREIGN KEY (FK_CLIENTES_ID_CLIENTE)
    REFERENCES CLIENTES (ID_CLIENTE)
    ON DELETE SET NULL;
 
ALTER TABLE PAGAMENTOS ADD CONSTRAINT FK_PAGAMENTOS_2
    FOREIGN KEY (FK_CLIENTES_ID_CLIENTE)
    REFERENCES CLIENTES (ID_CLIENTE)
    ON DELETE RESTRICT;
 
ALTER TABLE RESERVAS_RESERVA ADD CONSTRAINT FK_RESERVAS_RESERVA_2
    FOREIGN KEY (FK_CLIENTES_ID_CLIENTE)
    REFERENCES CLIENTES (ID_CLIENTE);
 
ALTER TABLE RESERVAS_RESERVA ADD CONSTRAINT FK_RESERVAS_RESERVA_3
    FOREIGN KEY (FK_QUARTOS_ID_QUARTO)
    REFERENCES QUARTOS (ID_QUARTO);
 
ALTER TABLE LIMPEZAS_FAZ_MANUTENCAO ADD CONSTRAINT FK_LIMPEZAS_FAZ_MANUTENCAO_2
    FOREIGN KEY (FK_FUNCIONARIOS_ID_FUNCIONARIO)
    REFERENCES FUNCIONARIOS (ID_FUNCIONARIO);
 
ALTER TABLE LIMPEZAS_FAZ_MANUTENCAO ADD CONSTRAINT FK_LIMPEZAS_FAZ_MANUTENCAO_3
    FOREIGN KEY (FK_QUARTOS_ID_QUARTO)
    REFERENCES QUARTOS (ID_QUARTO);