/* Modelo Relacional: */

CREATE TABLE CLIENTES (
    CLI_BAIRRO VARCHAR (50),
    CLI_NUMERO VARCHAR (5),
    CLI_CIDADE VARCHAR (50),
    CLI_CEP VARCHAR (9),
    CLI_ESTADO VARCHAR (2),
    CLI_NOME VARCHAR(255),
    CLI_CPF CHAR (11) ,
    CLI_RG VARCHAR (255),
    CLI_NASCIMENTO DATE,
    CLI_CELULAR VARCHAR(15),
    CLI_EMAIL VARCHAR(100),
    CLI_SEXO VARCHAR (10),
    CLI_SENHA VARCHAR(100),
    ID_CLIENTE INTEGER PRIMARY KEY
);

CREATE TABLE FUNCIONARIOS (
    FUN_NOME VARCHAR(255),
    FUN_CPF CHAR (11) ,
    FUN_RG VARCHAR (255),
    FUN_BAIRRO VARCHAR (50),
    FUN_NUMERO VARCHAR (5),
    FUN_CIDADE VARCHAR (50),
    FUN_CEP VARCHAR (9),
    FUN_ESTADO VARCHAR (2),
    FUN_SEXO VARCHAR (10),
    FUN_SENHA VARCHAR(100),
    FUN_EMAIL VARCHAR(100),
    FUN_CELULAR VARCHAR(15),
    FUN_NASCIMENTO DATE,
    FUN_TIPO VARCHAR(50),
    ID_FUNCIONARIO INTEGER PRIMARY KEY
);

CREATE TABLE FEEDBACKS (
    ID_FEEDBACK INT PRIMARY KEY,
    FEE_COMENTARIO VARCHAR(255),
    FK_CLIENTES_ID_CLIENTE INTEGER
);

CREATE TABLE PRODUTOS (
    PRD_ID INT PRIMARY KEY,
    PRD_NOME VARCHAR(25),
    PRD_PRECO DECIMAL(3,2),
    PRD_QUANTIDADE INT,
    FK_PEDIDOS_ID_PEDIDOS INT
);

CREATE TABLE PEDIDOS (
    PED_VALOR DECIMAL(3,2),
    ID_PEDIDOS INT PRIMARY KEY,
    PED_QTD INT,
    FK_CLIENTES_ID_CLIENTE INTEGER
);

CREATE TABLE PAGAMENTOS (
    PAG_ID INT PRIMARY KEY,
    PAG_VALOR_TOTAL DECIMAL(4,2),
    PAG_VALOR_PEDIDO DECIMAL(4,2),
    PAG_METODO VARCHAR(25),
    FK_CLIENTES_ID_CLIENTE INTEGER
);

CREATE TABLE QUARTOS (
    ID_QUARTO INT PRIMARY KEY,
    QRT_CAPACIDADE INT,
    QRT_TIPO_CAMA VARCHAR(80),
    QRT_DISPONIVEL BOOLEAN,
    QRT_PRECO_DIARIA DEC(3,2)
);

CREATE TABLE RESERVAS (
    FK_CLIENTES_ID_CLIENTE INTEGER,
    FK_QUARTOS_ID_QUARTO INT,
    RES_CHECKIN DATETIME,
    RES_CHECKOUT DATETIME,
    RES_QTD_HOSPEDES INT,
    ID_RESERVA INT PRIMARY KEY
);

CREATE TABLE LIMPEZAS (
    FK_FUNCIONARIOS_ID_FUNCIONARIO INTEGER,
    FK_QUARTOS_ID_QUARTO INT,
    ID_LIMPEZA INT PRIMARY KEY,
    LIM_LIMPO BOOLEAN,
    LIM_NOME_TAREFA VARCHAR(50),
    LIM_DATA_TAREFA DATETIME
);
 
ALTER TABLE FEEDBACKS ADD CONSTRAINT FK_FEEDBACKS_2
    FOREIGN KEY (FK_CLIENTES_ID_CLIENTE)
    REFERENCES CLIENTES (ID_CLIENTE)
    ON DELETE CASCADE;
 
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_2
    FOREIGN KEY (FK_PEDIDOS_ID_PEDIDOS)
    REFERENCES PEDIDOS (ID_PEDIDOS)
    ON DELETE RESTRICT;
 
ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_2
    FOREIGN KEY (FK_CLIENTES_ID_CLIENTE)
    REFERENCES CLIENTES (ID_CLIENTE)
    ON DELETE CASCADE;
 
ALTER TABLE PAGAMENTOS ADD CONSTRAINT FK_PAGAMENTOS_2
    FOREIGN KEY (FK_CLIENTES_ID_CLIENTE)
    REFERENCES CLIENTES (ID_CLIENTE)
    ON DELETE RESTRICT;
 
ALTER TABLE RESERVAS ADD CONSTRAINT FK_RESERVAS_2
    FOREIGN KEY (FK_CLIENTES_ID_CLIENTE)
    REFERENCES CLIENTES (ID_CLIENTE)
    ON DELETE RESTRICT;
 
ALTER TABLE RESERVAS ADD CONSTRAINT FK_RESERVAS_3
    FOREIGN KEY (FK_QUARTOS_ID_QUARTO)
    REFERENCES QUARTOS (ID_QUARTO)
    ON DELETE SET NULL;
 
ALTER TABLE LIMPEZAS ADD CONSTRAINT FK_LIMPEZAS_2
    FOREIGN KEY (FK_FUNCIONARIOS_ID_FUNCIONARIO)
    REFERENCES FUNCIONARIOS (ID_FUNCIONARIO)
    ON DELETE RESTRICT;
 
ALTER TABLE LIMPEZAS ADD CONSTRAINT FK_LIMPEZAS_3
    FOREIGN KEY (FK_QUARTOS_ID_QUARTO)
    REFERENCES QUARTOS (ID_QUARTO)
    ON DELETE SET NULL;