DROP DATABASE IF EXISTS chamaweb;
CREATE DATABASE chamaweb;
USE chamaweb;

CREATE TABLE USUARIOS (
    USR_MATRICULA VARCHAR(20) UNIQUE NOT NULL,
    USR_SENHA VARCHAR(255) NOT NULL,
    USR_EMAIL VARCHAR(255) NOT NULL,
    USR_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USR_NOME VARCHAR(255) NOT NULL,
    FK_TIPOS_TIP_ID INTEGER
);

CREATE TABLE CHAMADOS (
    CHA_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CHA_TITULO VARCHAR(255) NOT NULL,
    CHA_DATA VARCHAR(255) NOT NULL,
    CHA_DESCRICAO VARCHAR(255) NOT NULL,
    CHA_RESULTADO_AVALIACAO TINYINT(1),
    CHA_OBSERVACOES_AVALIACAO VARCHAR(1023),
    FK_MAQUINAS_MAQ_ID INTEGER,
    FK_USUARIOS_USR_ID INTEGER,
    FK_USUARIOS_USR_ID_TECNICO INTEGER,
    FK_CATEGORIAS_CAT_ID INTEGER,
    FK_PRIORIDADES_PRI_ID INTEGER,
    FK_ESTADOS_EST_ID INTEGER
);

CREATE TABLE MAQUINAS (
    MAQ_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    MAQ_MARCA VARCHAR(255) NOT NULL,
    MAQ_MODELO VARCHAR(255) NOT NULL,
    MAQ_PROCESSADOR VARCHAR(255) NOT NULL,
    MAQ_RAM VARCHAR(255) NOT NULL,
    MAQ_OS VARCHAR(255) NOT NULL,
    MAQ_ATIVO TINYINT(1) NOT NULL,
    FK_LABORATORIOS_LAB_ID INTEGER
);

CREATE TABLE LABORATORIOS (
    LAB_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LAB_NOME VARCHAR(255) NOT NULL UNIQUE,
    LAB_ATIVO TINYINT(1) NOT NULL
);

CREATE TABLE CATEGORIAS (
    CAT_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CAT_NOME VARCHAR(255) NOT NULL UNIQUE,
    CAT_ATIVO TINYINT(1) NOT NULL
);

CREATE TABLE ESTADOS (
    EST_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EST_NOME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE PRIORIDADES (
    PRI_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRI_NOME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE TIPOS (
    TIP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TIP_NOME VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE OPERACOES (
    OPS_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    OPS_DESCRICAO VARCHAR(1023) NOT NULL,
    FK_CHAMADOS_CHA_ID INTEGER,
    FK_USUARIOS_USR_ID INTEGER
);

CREATE TABLE MENSAGENS (
    MSG_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    MSG_CONTEUDO VARCHAR(255) NOT NULL,
    FK_CHAMADOS_CHA_ID INTEGER,
    FK_USUARIOS_USR_ID INTEGER
);
 
ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_2
    FOREIGN KEY (FK_TIPOS_TIP_ID)
    REFERENCES TIPOS (TIP_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE CHAMADOS ADD CONSTRAINT FK_CHAMADOS_2
    FOREIGN KEY (FK_MAQUINAS_MAQ_ID)
    REFERENCES MAQUINAS (MAQ_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE CHAMADOS ADD CONSTRAINT FK_CHAMADOS_3
    FOREIGN KEY (FK_USUARIOS_USR_ID)
    REFERENCES USUARIOS (USR_ID)
    ON DELETE RESTRICT;

ALTER TABLE CHAMADOS ADD CONSTRAINT FK_CHAMADOS_4
    FOREIGN KEY (FK_USUARIOS_USR_ID_TECNICO)
    REFERENCES USUARIOS (USR_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE CHAMADOS ADD CONSTRAINT FK_CHAMADOS_5
    FOREIGN KEY (FK_CATEGORIAS_CAT_ID)
    REFERENCES CATEGORIAS (CAT_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE CHAMADOS ADD CONSTRAINT FK_CHAMADOS_6
    FOREIGN KEY (FK_PRIORIDADES_PRI_ID)
    REFERENCES PRIORIDADES (PRI_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE CHAMADOS ADD CONSTRAINT FK_CHAMADOS_7
    FOREIGN KEY (FK_ESTADOS_EST_ID)
    REFERENCES ESTADOS (EST_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE MAQUINAS ADD CONSTRAINT FK_MAQUINAS_2
    FOREIGN KEY (FK_LABORATORIOS_LAB_ID)
    REFERENCES LABORATORIOS (LAB_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE OPERACOES ADD CONSTRAINT FK_OPERACOES_2
    FOREIGN KEY (FK_CHAMADOS_CHA_ID)
    REFERENCES CHAMADOS (CHA_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE OPERACOES ADD CONSTRAINT FK_OPERACOES_3
    FOREIGN KEY (FK_USUARIOS_USR_ID)
    REFERENCES USUARIOS (USR_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE MENSAGENS ADD CONSTRAINT FK_MENSAGENS_2
    FOREIGN KEY (FK_CHAMADOS_CHA_ID)
    REFERENCES CHAMADOS (CHA_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE MENSAGENS ADD CONSTRAINT FK_MENSAGENS_3
    FOREIGN KEY (FK_USUARIOS_USR_ID)
    REFERENCES USUARIOS (USR_ID)
    ON DELETE RESTRICT;