-- CreateTable
CREATE TABLE `MENSAGENS` (
    `MEN_ID` INTEGER NOT NULL,
    `MEN_MENSAGEM` VARCHAR(200) NOT NULL,
    `MEN_DATA` DATETIME(3) NOT NULL,
    `fk_topico_id` INTEGER NOT NULL,
    `fk_user_id` INTEGER NOT NULL,

    PRIMARY KEY (`MEN_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `MENSAGENS` ADD CONSTRAINT `MENSAGENS_fk_topico_id_fkey` FOREIGN KEY (`fk_topico_id`) REFERENCES `TOPICOS`(`TOP_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `MENSAGENS` ADD CONSTRAINT `MENSAGENS_fk_user_id_fkey` FOREIGN KEY (`fk_user_id`) REFERENCES `USUARIOS`(`USR_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
